### ISSUE TITLE
mi6 fails to run on Windows

### ISSUE THREAD

**Issue by azawawi** [skaji/mi6#6] opened 2016-03-06 09:30 UTC
While adding support for mi6 in [Atom Perl 6 Editor Tools](https://github.com/azawawi/atom-perl6-editor-tools/releases/tag/v0.9.18), I encountered the following error on Windows 7 64-bit:

```
C:\Users\azawawi>mi6
===SORRY!=== Error while compiling C:\Users\azawawi\rakudobrew\moar
-2016.01\install\share\perl6\site/resources/19DFC05B99EC4E218A1A8D9A1B966919724D
E593
Two terms in a row
at C:\Users\azawawi\rakudobrew\moar-2016.01\install\share\perl6\sit
e/resources/19DFC05B99EC4E218A1A8D9A1B966919724DE593:1
------> @<HERE> perl6 %~dpn0 %*
    expecting any of:
        infix
        infix stopper
        statement end
        statement modifier
        statement modifier loop
```

**Comment by skaji** [comment] 2016-03-06 13:10
Is this issue due to mi6 having own `.bat` in https://github.com/skaji/mi6/tree/master/bin ?

Note: I don't have perl6 Windows environment.

**Comment by azawawi** [comment] 2016-03-27 10:59
Sorry for being slow on this one. I will test it on windows and report back.

**Comment by azawawi** [comment] 2016-03-27 14:02
Build progress on my fork (on Windows):
https://ci.appveyor.com/project/azawawi/mi6/build/1.0.1

**Comment by skaji** [comment] 2016-03-28 15:58
build failed ?

**Comment by ufobat** [comment] 2018-12-24 09:57
I would highly recommend to have  AppVeyor CI on this project.
But, I can confirm that `mi6` works on my windows. So this ticket could be closed i think.

**Comment by skaji** [comment] 2022-03-12 07:07
Closing in favor of  #146

**Closed by skaji** 2022-03-12 07:07 UTC
